### ISSUE TITLE
Fork and LICENSE

### ISSUE THREAD

**Issue by xbc5** [martinring/markdown-it-table-captions#3]
I hope you don't mind, I forked this repo (permanently), and added the missing LICENSE. I set it to MIT, and put you as the copyright holder:

https://github.com/xbc5/markdown-it-table-captions/commit/95c982cdec553e1f87242d665f6132390aab8095

If you have an issue with that I will change it.

Thanks.

**Comment by xbc5** [comment]
Closing because I will use `markdown-it-multimd-table` instead (which is maintained); deleting the fork. Sorry to bother you.

**Comment by martinring** [comment]
no worries
